// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Animal struct {
	ID      int64  `json:"id"`
	Nombre  string `json:"nombre"`
	Raza    string `json:"raza"`
	IDDueno int64  `json:"id_dueno"`
	Precio  string `json:"precio"`
}

type Publicacion struct {
	ID         int64  `json:"id"`
	IDAnimal   int64  `json:"id_animal"`
	Precio     string `json:"precio"`
	IDVendedor int64  `json:"id_vendedor"`
}

type Usuario struct {
	ID       int64          `json:"id"`
	Nombre   string         `json:"nombre"`
	Apellido string         `json:"apellido"`
	Contacto sql.NullString `json:"contacto"`
}

type Ventum struct {
	ID            int64        `json:"id"`
	IDPublicacion int64        `json:"id_publicacion"`
	IDVendedor    int64        `json:"id_vendedor"`
	IDComprador   int64        `json:"id_comprador"`
	Fecha         sql.NullTime `json:"fecha"`
}
