// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publicacion.sql

package db

import (
	"context"
)

const createPublicacion = `-- name: CreatePublicacion :one

INSERT INTO Publicacion (id_animal, precio, id_vendedor)
VALUES ($1, $2, $3)
RETURNING id, id_animal, precio, id_vendedor
`

type CreatePublicacionParams struct {
	IDAnimal   int64  `json:"id_animal"`
	Precio     string `json:"precio"`
	IDVendedor int64  `json:"id_vendedor"`
}

// ==========================================
// PUBLICACION
// ==========================================
func (q *Queries) CreatePublicacion(ctx context.Context, arg CreatePublicacionParams) (Publicacion, error) {
	row := q.db.QueryRowContext(ctx, createPublicacion, arg.IDAnimal, arg.Precio, arg.IDVendedor)
	var i Publicacion
	err := row.Scan(
		&i.ID,
		&i.IDAnimal,
		&i.Precio,
		&i.IDVendedor,
	)
	return i, err
}

const getPublicacion = `-- name: GetPublicacion :one
SELECT id, id_animal, precio, id_vendedor 
FROM Publicacion 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPublicacion(ctx context.Context, id int64) (Publicacion, error) {
	row := q.db.QueryRowContext(ctx, getPublicacion, id)
	var i Publicacion
	err := row.Scan(
		&i.ID,
		&i.IDAnimal,
		&i.Precio,
		&i.IDVendedor,
	)
	return i, err
}

const listPublicacionesActivas = `-- name: ListPublicacionesActivas :many
SELECT id, id_animal, precio, id_vendedor 
FROM Publicacion 
ORDER BY id DESC
`

func (q *Queries) ListPublicacionesActivas(ctx context.Context) ([]Publicacion, error) {
	rows, err := q.db.QueryContext(ctx, listPublicacionesActivas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publicacion
	for rows.Next() {
		var i Publicacion
		if err := rows.Scan(
			&i.ID,
			&i.IDAnimal,
			&i.Precio,
			&i.IDVendedor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
