// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Usuario.sql

package db

import (
	"context"
	"database/sql"
)

const createUsuario = `-- name: CreateUsuario :one

INSERT INTO Usuario (nombre, apellido, contacto)
VALUES ($1, $2, $3)
RETURNING id, nombre, apellido, contacto
`

type CreateUsuarioParams struct {
	Nombre   string         `json:"nombre"`
	Apellido string         `json:"apellido"`
	Contacto sql.NullString `json:"contacto"`
}

// ==========================================
// USUARIO
// ==========================================
func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario, arg.Nombre, arg.Apellido, arg.Contacto)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Contacto,
	)
	return i, err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id, nombre, apellido, contacto 
FROM Usuario 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUsuario(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Contacto,
	)
	return i, err
}
