// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venta.sql

package db

import (
	"context"
	"database/sql"
)

const createVenta = `-- name: CreateVenta :one
INSERT INTO Venta (id_publicacion, id_vendedor, id_comprador)
VALUES ($1, $2, $3)
RETURNING id, id_publicacion, id_vendedor, id_comprador, fecha
`

type CreateVentaParams struct {
	IDPublicacion int64 `json:"id_publicacion"`
	IDVendedor    int64 `json:"id_vendedor"`
	IDComprador   int64 `json:"id_comprador"`
}

func (q *Queries) CreateVenta(ctx context.Context, arg CreateVentaParams) (Ventum, error) {
	row := q.db.QueryRowContext(ctx, createVenta, arg.IDPublicacion, arg.IDVendedor, arg.IDComprador)
	var i Ventum
	err := row.Scan(
		&i.ID,
		&i.IDPublicacion,
		&i.IDVendedor,
		&i.IDComprador,
		&i.Fecha,
	)
	return i, err
}

const deleteVenta = `-- name: DeleteVenta :exec
DELETE FROM Venta
WHERE id = $1
`

func (q *Queries) DeleteVenta(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVenta, id)
	return err
}

const getVenta = `-- name: GetVenta :one
SELECT id, id_publicacion, id_vendedor, id_comprador, fecha 
FROM Venta 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVenta(ctx context.Context, id int64) (Ventum, error) {
	row := q.db.QueryRowContext(ctx, getVenta, id)
	var i Ventum
	err := row.Scan(
		&i.ID,
		&i.IDPublicacion,
		&i.IDVendedor,
		&i.IDComprador,
		&i.Fecha,
	)
	return i, err
}

const listVentasByComprador = `-- name: ListVentasByComprador :many
SELECT id, id_publicacion, id_vendedor, id_comprador, fecha 
FROM Venta 
WHERE id_comprador = $1 
ORDER BY fecha DESC
`

func (q *Queries) ListVentasByComprador(ctx context.Context, idComprador int64) ([]Ventum, error) {
	rows, err := q.db.QueryContext(ctx, listVentasByComprador, idComprador)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ventum
	for rows.Next() {
		var i Ventum
		if err := rows.Scan(
			&i.ID,
			&i.IDPublicacion,
			&i.IDVendedor,
			&i.IDComprador,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVentasConDetalle = `-- name: ListVentasConDetalle :many
SELECT v.id AS venta_id, v.fecha, 
       u_comp.nombre AS comprador_nombre, 
       u_vend.nombre AS vendedor_nombre, 
       p.precio
FROM Venta v
JOIN Usuario u_comp ON v.id_comprador = u_comp.id
JOIN Usuario u_vend ON v.id_vendedor = u_vend.id
JOIN Publicacion p ON v.id_publicacion = p.id
`

type ListVentasConDetalleRow struct {
	VentaID         int64        `json:"venta_id"`
	Fecha           sql.NullTime `json:"fecha"`
	CompradorNombre string       `json:"comprador_nombre"`
	VendedorNombre  string       `json:"vendedor_nombre"`
	Precio          string       `json:"precio"`
}

func (q *Queries) ListVentasConDetalle(ctx context.Context) ([]ListVentasConDetalleRow, error) {
	rows, err := q.db.QueryContext(ctx, listVentasConDetalle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVentasConDetalleRow
	for rows.Next() {
		var i ListVentasConDetalleRow
		if err := rows.Scan(
			&i.VentaID,
			&i.Fecha,
			&i.CompradorNombre,
			&i.VendedorNombre,
			&i.Precio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenta = `-- name: UpdateVenta :one
UPDATE Venta
SET id_publicacion = $2,
    id_vendedor = $3,
    id_comprador = $4
WHERE id = $1
RETURNING id, id_publicacion, id_vendedor, id_comprador, fecha
`

type UpdateVentaParams struct {
	ID            int64 `json:"id"`
	IDPublicacion int64 `json:"id_publicacion"`
	IDVendedor    int64 `json:"id_vendedor"`
	IDComprador   int64 `json:"id_comprador"`
}

func (q *Queries) UpdateVenta(ctx context.Context, arg UpdateVentaParams) (Ventum, error) {
	row := q.db.QueryRowContext(ctx, updateVenta,
		arg.ID,
		arg.IDPublicacion,
		arg.IDVendedor,
		arg.IDComprador,
	)
	var i Ventum
	err := row.Scan(
		&i.ID,
		&i.IDPublicacion,
		&i.IDVendedor,
		&i.IDComprador,
		&i.Fecha,
	)
	return i, err
}
